/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROGRAM_H_RPCGEN
#define _PROGRAM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int num1;
	int num2;
};
typedef struct numbers numbers;

#define PROGRAM 0x23451111
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDITION 1
extern  int * addition_1(numbers *, CLIENT *);
extern  int * addition_1_svc(numbers *, struct svc_req *);
#define SUBTRACTION 2
extern  int * subtraction_1(numbers *, CLIENT *);
extern  int * subtraction_1_svc(numbers *, struct svc_req *);
#define MULTIPLICATION 3
extern  int * multiplication_1(numbers *, CLIENT *);
extern  int * multiplication_1_svc(numbers *, struct svc_req *);
#define DIVISION 4
extern  int * division_1(numbers *, CLIENT *);
extern  int * division_1_svc(numbers *, struct svc_req *);
extern int program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDITION 1
extern  int * addition_1();
extern  int * addition_1_svc();
#define SUBTRACTION 2
extern  int * subtraction_1();
extern  int * subtraction_1_svc();
#define MULTIPLICATION 3
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define DIVISION 4
extern  int * division_1();
extern  int * division_1_svc();
extern int program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROGRAM_H_RPCGEN */
